version: "3.9"

services:
  app:
    build: .
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - db
    networks:
      - content-service-network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - content-service-network
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  bundle:

networks:
  content-service-network:
